-- Подключаем ваши разделенные файлы (они должны лежать в ~/.config/hypr/hyprland/)
require("hyprland.monitors")
require("hyprland.autostart")
require("hyprland.env")
require("hyprland.keybindings")
require("hyprland.general")
