hl.on("hyprland.start", function()
  hl.exec_cmd("hypridle")
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("mako")
  hl.exec_cmd("waybar")
  hl.exec_cmd("kitty", { workspace = 1 })
  hl.exec_cmd("firefox", { workspace = 2 })
  hl.exec_cmd("Telegram", { workspace = 3 })
end)
