hl.on("hyprland.start", function ()
	hl.exec_cmd("hypridle")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("mako")
	hl.exec_cmd("waybar")
	hl.exec_cmd("kitty")
	hl.exec_cmd("firefox")
	hl.exec_cmd("Telegram")
end)